testsmagistratura/istgv/urls.py
from django.urls import path

from istgv import views

app_name = 'istgv'
urlpatterns = [
    path('quest/', views.quest, name='quest'),
    path('<int:quest_id>/verify/', views.verify, name='verify'),
]

testsmagistratura/isviv/urls.py
from django.urls import path

from isviv import views

app_name = 'isviv'
urlpatterns = [
    path('', views.index, name='index'),
    path('quest/', views.quest, name='quest'),
    path('<int:quest_id>/verify/', views.verify, name='verify'),
]

testsmagistratura/mzhg/urls.py
from django.urls import path

from mzhg import views

app_name = 'mzhg'
urlpatterns = [
    path('quest/', views.quest, name='quest'),
    path('<int:quest_id>/verify/', views.verify, name='verify'),
]

testsmagistratura/oask/urls.py
from django.urls import path

from oask import views

app_name = 'oask'
urlpatterns = [
    path('quest/', views.quest, name='quest'),
    path('<int:quest_id>/verify/', views.verify, name='verify'),
]

testsmagistratura/testsmagistratura/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('isviv.urls')),
    path('istgv/', include('istgv.urls')),
    path('tosous/', include('tosous.urls')),
    path('gidravlika/', include('gidravlika.urls')),
    path('ecology/', include('ecology.urls')),
    path('oask/', include('oask.urls')),
    path('zakon/', include('zakon.urls')),
    path('vivmgsu/', include('vivmgsu.urls')),
    path('tezis/', include('tezis.urls')),
    path('geodezy/', include('geodezy.urls')),
    path('mathematics/', include('mathematics.urls')),
    path('metrology/', include('metrology.urls')),
    path('soilmechanics/', include('soilmechanics.urls')),
    path('mzhg/', include('mzhg.urls')),
    path('constructionmaterials/', include('constructionmaterials.urls')),
    path('tsposp/', include('tsposp.urls')),
    path('physics/', include('physics.urls')),
    path('chemistry/', include('chemistry.urls')),
    path('economyc/', include('economyc.urls')),
    path('electrician/', include('electrician.urls')),
    path('admin/', admin.site.urls),
]

testsmagistratura/tezis/urls.py
from django.urls import path

from tezis import views

app_name = 'tezis'
urlpatterns = [
    path('quest/', views.quest, name='quest'),
    path('<int:quest_id>/verify/', views.verify, name='verify'),
]

testsmagistratura/zakon/urls.py
from django.urls import path

from zakon import views

app_name = 'zakon'
urlpatterns = [
    path('quest/', views.quest, name='quest'),
    path('<int:quest_id>/verify/', views.verify, name='verify'),
]

testsmagistratura/isviv/views.py
import random

from django.shortcuts import render, get_object_or_404

from .models import Question


def index(request):
    title = 'Начало'
    request.session['list_q'] = []
    request.session['begin_test'] = True
    return render(request, 'isviv/index.html', {'title': title})


def quest(request):
    q, c = quest_base(request, Question)
    context = {'quest': q,
               'choices': c,
               'title': 'Вопрос',
               'tema': 'Водоснабжение и водоотведение',
               'action': 'isviv:verify'}

    return render(request, 'isviv/quest.html', context)

def quest_base(request, model_tema):
    if request.session.get('begin_test', True):
        questions = model_tema.objects.all()
        list_q = []
        for question in questions:
            list_q.append(question.pk)
        random.shuffle(list_q)
        request.session['list_q'] = list_q
        request.session['begin_test'] = False

    list_q = request.session.get('list_q', [])

    q_id = list_q.pop()
    request.session['list_q'] = list_q

    # result = Question.objects.count()
    # a = random.choice(range(result))
    q = model_tema.objects.get(pk=q_id)
    c = list(q.choice_set.all())
    random.shuffle(c)
    return q, c



def verify(request, quest_id):
    a, q, ch, next_q = verify_base(request, Question, quest_id)
    context = {'result': a,
               'question': q,
               'selected_choice': ch,
               'title': 'Проверка',
               'tema': 'Водоснабжение и водоотведение',
               'next_q': next_q,
               'next_link': 'isviv:quest'}

    return render(request, 'isviv/verify.html', context)

def verify_base(request, model_tema, quest_id):
    q = get_object_or_404(model_tema, pk=quest_id)

    try:
        selected_choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError):
        # Redisplay the question voting form.
        ch = ''
        a = 'Не верно'
    else:
        ch = selected_choice.choice
        if selected_choice.correct:
            a = 'Правильно'
        else:
            a = 'Не верно'

    list_q = request.session.get('list_q', [])
    next_q = True
    if not list_q:
        next_q = False

    return a, q, ch, next_q

testsmagistratura/isviv/templates/isviv/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1> {{ tema }} </h1>
    {% block content %}
    {% endblock %}
</body>
</html>

testsmagistratura/isviv/templates/isviv/index.html
{% extends 'isviv/base.html' %}

    {% block content %}
    <h1>Главное меню</h1>
    <p><a href="{% url 'isviv:quest' %}" >Водоснабжение и водоотведение</a></p>
    <p><a href="{% url 'istgv:quest' %}" >Теплогазоснабжение и вентиляция</a></p>
    <p><a href="{% url 'tosous:quest' %}" >Технология и организация строительства</a></p>
    <p><a href="{% url 'gidravlika:quest' %}" >Гидравлика</a></p>
    <p><a href="{% url 'ecology:quest' %}" >Экология</a></p>
    <p><a href="{% url 'oask:quest' %}" >Основы архитектуры и СК</a></p>
    <p><a href="{% url 'zakon:quest' %}" >Основы законодательства</a></p>
    <p><a href="{% url 'vivmgsu:quest' %}" >Водоснабжение МГСУ</a></p>
    <p><a href="{% url 'tezis:quest' %}" >Техническая эксплуатация ЗиС</a></p>
    <p><a href="{% url 'geodezy:quest' %}" >Геодезия МГ</a></p>
    <p><a href="{% url 'mathematics:quest' %}" >Математика МГ</a></p>
    <p><a href="{% url 'metrology:quest' %}" >Метрология МГ</a></p>
    <p><a href="{% url 'soilmechanics:quest' %}" >Механика грунтов МГ</a></p>
    <p><a href="{% url 'mzhg:quest' %}" >МЖГ МГ</a></p>
    <p><a href="{% url 'constructionmaterials:quest' %}" >Строительные материалы МГ</a></p>
    <p><a href="{% url 'tsposp:quest' %}" >ТСП ОСП МГ</a></p>
    <p><a href="{% url 'physics:quest' %}" >Физика МГ</a></p>
    <p><a href="{% url 'chemistry:quest' %}" >Химия МГ</a></p>
    <p><a href="{% url 'economyc:quest' %}" >Экономика МГ</a></p>
    <p><a href="{% url 'electrician:quest' %}" >Электротехника МГ</a></p>
    {% endblock %}

testsmagistratura/isviv/templates/isviv/quest.html
{% extends 'isviv/base.html' %}

    {% block content %}
    <form action="{% url action quest.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ quest.question }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in choices %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Ответить">
    </form>
    {% endblock %}

testsmagistratura/isviv/templates/isviv/verify.html
{% extends 'isviv/base.html' %}

    {% block content %}
    <h2>{{ question.question }}</h2>
    <h2>{{ selected_choice }}</h2>
    <h3>{{ result }}</h3>
    <a href="{% url 'isviv:index' %}">На главную</a>
    {% if next_q %}
    <a href="{% url next_link %}">Следующий вопрос</a>
    {% endif %}
    {% endblock %}